import painting3d from './Images/3dpainting.jpg'
import birdsketch from './Images/birdsketch.jpg'
import catsketch from './Images/catsketch.jpg'
import dnyaneshwar from './Images/dnyaneshwar.jpg'
import girlsketch from './Images/girlsketch.jpg'
import krishnapainting from './Images/krishnapainting.jpg'
import shahrukh from './Images/shahrukh.jpg'
import shiva from './Images/shiva.jpg'
import tradingtastes from './Images/tradingtastes.jpg'

import music from './pictures/music.JPG'

import brochure from './pictures/brochure.JPG'
import cow from './pictures/cow.JPG'
import designspace from './pictures/designspace.JPG'
import firstpage from './pictures/firstpage.JPG'
import illustration from './pictures/illustration.JPG'
import invelope1 from './pictures/invelope1.JPG'
import invelope2 from './pictures/invelope2.JPG'
import invelope3 from './pictures/invelope3.JPG'
import letterhead1 from './pictures/letterhead1.JPG'
import letterhead2 from './pictures/letterhead2.JPG'
import letterhead3 from './pictures/letterhead3.JPG'
import logo1 from './pictures/logo1.JPG'
import logo2 from './pictures/logo2.JPG'
import logo3 from './pictures/logo3.JPG'
import logo4 from './pictures/logo4.JPG'
import logo5 from './pictures/logo5.JPG'
import logo6 from './pictures/logo6.JPG'
import logo7 from './pictures/logo7.JPG'
import pack1 from './pictures/pack1.JPG'
import pack2 from './pictures/pack2.JPG'
import pack3 from './pictures/pack3.JPG'
import pack4 from './pictures/pack4.JPG'
import pack5 from './pictures/pack5.JPG'
import pack6 from './pictures/pack6.JPG'
import pack7 from './pictures/pack7.JPG'
import pack8 from './pictures/pack8.JPG'
import pamphlet from './pictures/pamphlet.JPG'
import perspective from './pictures/perspective.JPG'
import poster1 from './pictures/poster1.JPG'
import poster2 from './pictures/poster2.JPG'
import poster3 from './pictures/poster3.JPG'
import poster4 from './pictures/poster4.JPG'
import poster5 from './pictures/poster5.JPG'
import secendpage from './pictures/secendpage.JPG'
import texture from './pictures/texture.JPG'
import visitingcard1 from './pictures/visitingcard1.JPG'
import visitingcard2 from './pictures/visitingcard2.JPG'
import visitingcard3 from './pictures/visitingcard3.JPG'


export { painting3d, birdsketch, catsketch, dnyaneshwar, girlsketch, krishnapainting, shiva, tradingtastes }
export { music, brochure, cow, designspace, firstpage, illustration, invelope1, invelope2, invelope3, letterhead1, letterhead2, letterhead3,
          logo1, logo2, logo3, logo4, logo5, logo6, logo7, pack1, pack2, pack3, pack4, pack5, pack6, pack7, pack8,
        pamphlet, perspective, poster1, poster2, poster3, poster4, poster5, secendpage, texture, shahrukh, visitingcard1, visitingcard2, visitingcard3}
